/*Crear STREAM*/
CREATE STREAM TRANSACCIONES (fecha VARCHAR, tarjeta VARCHAR, tipo VARCHAR, marca VARCHAR,  dispositivo VARCHAR, tecnologia VARCHAR, 
producto VARCHAR, estado VARCHAR, importe DOUBLE, comercio VARCHAR, mcc VARCHAR, rubro varchar, ciudad VARCHAR )
  WITH (kafka_topic='tran-tarjeta', value_format='json', partitions=1);

/**RESUMEN DE TRANSACCIONES POR MARCA**/
CREATE TABLE TRANSACCION_X_MARCA AS
SELECT MARCA,  
COUNT(*) CANTIDAD, SUM(importe)TOTAL
from TRANSACCIONES
GROUP BY MARCA
EMIT CHANGES;

/**RESUMEN DE TRANSACCIONES POR ESTADO**/
CREATE TABLE TRANSACCION_X_ESTADO AS
SELECT ESTADO,
COUNT(*) CANTIDAD, SUM(importe)TOTAL
from TRANSACCIONES
GROUP BY ESTADO
EMIT CHANGES;

/**RESUMEN DE TRANSACCIONES POR CIUDAD**/
CREATE TABLE TRANSACCIONES_X_CIUDAD AS
SELECT CIUDAD,
count(*) CANTIDAD
from TRANSACCIONES
GROUP BY CIUDAD
EMIT CHANGES;

/**RESUMEN DE TRANSACCIONES POR RUBRO**/
CREATE TABLE TRANSACCIONES_X_RUBRO AS
SELECT RUBRO,
count(*) CANTIDAD, SUM(IMPORTE)
from TRANSACCIONES
GROUP BY RUBRO
EMIT CHANGES;

/**RESUMEN DE TRANSACCIONES POR DISPOSITIVO**/
CREATE TABLE TRANSACCIONES_X_CIUDAD AS
SELECT DISPOSITIVO,
count(*) CANTIDAD
from TRANSACCIONES
GROUP BY DISPOSITIVO
EMIT CHANGES;

/**RESUMEN DE TRANSACCIONES POR TECNOLOGIA**/
CREATE TABLE TRANSACCIONES_X_CIUDAD AS
SELECT TECNOLOGIA,
count(*) CANTIDAD
from TRANSACCIONES
GROUP BY TECNOLOGIA
EMIT CHANGES;